export const siteConfig = {
  name: "Favour Aibangbee",
  title: "Fullstack & Backend Engineer",
  email: "aibangbeefavour509@gmail.com",
  phone: "07043769928",
  location: "Benin City, Nigeria",
  available: true,
  github: "https://github.com/John-Favour",
  linkedin: "https://www.linkedin.com/in/favour-john-ai",
  twitter: "https://x.com/_DsEnterprise",
  twitterHandle: "@_DsEnterprise",
  domain: "favour-aibangbee.netlify.app",
};

export const skills = [
  { category: "Languages", items: ["JavaScript ES6+", "TypeScript", "HTML5", "CSS3"] },
  { category: "Frontend", items: ["React.js", "Next.js", "React Native", "Tailwind CSS", "Bootstrap"] },
  { category: "Backend", items: ["Node.js", "Express.js", "REST APIs", "JWT Auth", "Paystack", "Stripe"] },
  { category: "Databases", items: ["MongoDB", "PostgreSQL", "MySQL"] },
  { category: "Tools & Workflow", items: ["Git", "GitHub", "Postman", "VS Code", "Agile/Scrum", "Flutter"] },
  { category: "Engineering", items: ["AutoCAD", "SolidWorks", "Ship Stability Analysis", "Naval Architecture"] },
];

export const experience = [
  {
    period: "Jan 2025 – Present",
    company: "Self-Employed",
    role: "Fullstack Developer · Freelance",
    current: true,
    bullets: [
      "Built and deployed websites and web apps for engineering firms across the full project lifecycle from requirements gathering to production deployment.",
      "Integrated WhatsApp chat, quotation forms, and embedded video for a solar and electrical engineering client.",
      "Delivered end-to-end solutions tailored for Nigeria's engineering sector.",
    ],
  },
  {
    period: "2023 – 2025",
    company: "Givitec Ltd",
    role: "Junior Software Developer",
    current: false,
    bullets: [
      "Integrated Paystack and Stripe via a unified Node.js service layer with JWT authentication and RESTful API architecture.",
      "Built Givitec.com a multi-tenant CBT SaaS platform using React.js, Node.js/Express, and Context API state management.",
      "Developed Dannic Inspo a fullstack inspiration board app with lazy loading and ImageKit cloud media storage.",
      "Built a Hospital Inventory System with RBAC, CRUD operations, PostgreSQL, and real-time stock alerts.",
      "Deployed school management portals with React.js dashboards, sessionbased auth, and MongoDB backend.",
      "Collaborated in an agile team using Git/GitHub for version control and code reviews.",
    ],
  },
];

export const projects = [
  {
    slug: "sendstack-email-api",
    num: "01",
    name: "SendStack Email API",
    tagline: "Multi-tenant email infrastructure in Go",
    shortDesc: "Multi-tenant email API with PostgreSQL Row-Level Security for database-layer tenant isolation and unified provider abstraction.",
    problem: "Most email APIs offer no true multi-tenancy — they filter data at the app layer, which is vulnerable to bugs and leakage. Organizations building SaaS products need guaranteed data isolation at the lowest level possible.",
    solution: "SendStack enforces tenant isolation using PostgreSQL Row-Level Security (RLS) — the same pattern used by Supabase. Each tenant's data is physically separated at the database layer, not just filtered in queries. A unified provider abstraction layer means tenants can switch email providers without changing their integration.",
    stack: [
      { name: "PostgreSQL", reason: "Selected over MongoDB because RLS (Row-Level Security) is a PostgreSQL-native feature that enables true database-layer multi-tenancy — impossible to replicate cleanly in document databases." },
      { name: "Row-Level Security (RLS)", reason: "Enforces data isolation at the database layer rather than the application layer, eliminating an entire class of data leakage bugs common in multi-tenant apps." },
      { name: "REST API", reason: "Simple, well-understood interface that integrates easily with any language or framework a tenant might use." },
    ],
    features: ["Multi-tenant architecture via PostgreSQL RLS", "Unified email provider abstraction (SendGrid, Mailgun, SMTP)", "API key authentication with scoped permissions", "Per-tenant rate limiting", "Email delivery logging and status tracking", "Tenant provisioning endpoints"],
    tags: [ "PostgreSQL", "RLS", "REST API", "Multi-tenant"],
  },
  {
    slug: "givitec-cbt-platform",
    num: "02",
    name: "Givitec CBT Platform",
    tagline: "Production SaaS exam platform for institutions",
    shortDesc: "Live multi-tenant Computer-Based Testing SaaS with real-time exam engine, user management, and Paystack subscription billing.",
    problem: "Schools and institutions in Nigeria rely on paper-based exams which are slow, expensive, and prone to human error in marking. Existing CBT solutions are either too expensive or not built for the Nigerian education context.",
    solution: "Givitec is a full SaaS platform where schools register, onboard students, create and schedule exams, and receive automatically graded results in real time. Multi-tenancy ensures each school's data is completely isolated while sharing the same infrastructure, keeping costs low.",
    stack: [
      { name: "React.js", reason: "Component-based architecture made it easy to build the complex exam UI — timers, question navigation, answer states — as reusable, testable pieces." },
      { name: "Node.js + Express", reason: "Fast non-blocking I/O is critical for a platform where many students submit exam answers simultaneously. Express gave full control over the API architecture." },
      { name: "MongoDB", reason: "Flexible schema was ideal for exam data — different question types, varied metadata, and nested answer structures that would be cumbersome in a rigid relational schema." },
      { name: "Context API", reason: "Chosen over Redux for its simplicity — the app state (user session, current exam, answers) was complex enough to need global state but not complex enough to warrant Redux overhead." },
      { name: "Paystack", reason: "Nigeria-first payment gateway with excellent local bank support, low fees, and a developer-friendly API for subscription billing." },
    ],
    features: ["Multi-tenant SaaS with isolated school data", "Role-based access: Super Admin, School Admin, Teacher, Student", "Live exam engine with countdown timer and auto-submit", "Real-time grading and result processing", "Exam scheduling with date/time and group targeting", "Paystack subscription billing for school plans"],
    tags: ["React.js", "Node.js", "MongoDB", "JWT", "Paystack", "SaaS"],
  },
  {
    slug: "hospital-inventory-system",
    num: "03",
    name: "Hospital Inventory System",
    tagline: "RBAC stock management for healthcare",
    shortDesc: "Role-based hospital inventory system with real-time stock tracking, automatic low-stock alerts, and full audit logging.",
    problem: "A hospital was managing medical supplies, equipment, and consumables using spreadsheets — making it impossible to track real-time stock levels, identify shortages before they became critical, or audit who changed what.",
    solution: "A centralised web-based inventory system with role-based access control. Admins manage everything, Managers edit stock, Staff only view. Every stock change is logged with a timestamp and user. Automatic alerts fire the moment any item drops below its defined minimum threshold.",
    stack: [
      { name: "React.js", reason: "Needed a dynamic dashboard that updates stock levels and alerts in real time without full page reloads — React's state model was perfect for this." },
      { name: "Node.js + Express", reason: "REST API backend that handles CRUD operations, RBAC middleware, and alert logic cleanly." },
      { name: "PostgreSQL", reason: "Healthcare data requires strict relational integrity. PostgreSQL's ACID compliance and foreign key constraints ensure no orphaned records or inconsistent stock movements." },
      { name: "JWT + RBAC", reason: "JWT for stateless authentication, with a custom RBAC middleware layer that checks role permissions on every protected route before executing any operation." },
    ],
    features: ["Role-Based Access Control: Admin, Manager, Staff", "Full CRUD for inventory items and categories", "Real-time stock level tracking with minimum thresholds", "Automatic low-stock alerts", "Immutable stock movement audit log", "Search and filter by name, category, supplier, status", "Dashboard summary with charts and activity feed"],
    tags: ["React.js", "Node.js", "PostgreSQL", "RBAC", "JWT"],
  },
  {
    slug: "dannic-inspo-board",
    num: "04",
    name: "Dannic Inspo Board",
    tagline: "Pinterest-style inspiration board with ImageKit",
    shortDesc: "Fullstack inspiration board with ImageKit cloud storage, real-time image transformations, lazy loading, and a public discovery feed.",
    problem: "Creative professionals save inspiration across WhatsApp, screenshots, browser bookmarks, and notes apps — scattered with no structure. They needed one clean place to collect, organize, and revisit ideas with fast performance even on slow Nigerian internet connections.",
    solution: "A Pinterest-style board app where users create boards, pin images and quotes, and browse a public feed. ImageKit handles all media — uploads, storage, CDN delivery, and real-time transformations. Lazy loading with IntersectionObserver ensures images only load when visible, keeping the app fast on any connection.",
    stack: [
      { name: "React.js", reason: "The masonry-style board layout and infinite scroll feed required React's component model and state management for smooth interactions." },
      { name: "Node.js + Express", reason: "RESTful API handling auth, board management, media upload signatures, and feed queries." },
      { name: "MongoDB", reason: "Flexible document schema was ideal for pin data — varying content types (images, quotes, links) with different metadata per type." },
      { name: "ImageKit", reason: "Chosen over Cloudinary for its generous free tier, built-in image transformation API (resize, crop, compress, filters via URL params), and faster CDN performance in Africa." },
      { name: "Lazy Loading (IntersectionObserver)", reason: "Native browser API — no extra library needed. Loads images only when they enter the viewport, critical for performance on slow connections." },
    ],
    features: ["ImageKit upload, storage, and CDN delivery", "Real-time image transformations via URL API", "Board creation and collection management", "Lazy loading with IntersectionObserver", "Public discovery feed", "Search and filter by title or tag", "JWT authentication with protected boards"],
    tags: ["React.js", "Node.js", "MongoDB", "ImageKit", "JWT"],
  },
  {
    slug: "school-management-portal",
    num: "05",
    name: "School Management Portal",
    tagline: "Full school administration system",
    shortDesc: "Comprehensive school admin system covering student enrollment, staff management, attendance tracking, academic records, and report card generation.",
    problem: "A secondary school was managing everything on paper and Excel — student records, attendance, exam scores, and report cards were all manual processes prone to errors, loss, and delays. Teachers spent hours calculating grades instead of teaching.",
    solution: "A centralised school management portal with role-based dashboards for Admins, Teachers, and Parents. Automates grade calculation, generates report cards per term, and gives each role exactly the data they need — no more, no less.",
    stack: [
      { name: "React.js", reason: "Dashboard-heavy application with multiple data tables, charts, and forms — React's component model made it manageable and maintainable." },
      { name: "Node.js + Express", reason: "Clean REST API for all school operations — students, staff, classes, attendance, scores." },
      { name: "MongoDB", reason: "School data is highly variable — different subjects per class, varying term structures, optional fields. MongoDB's flexible schema handled this better than a rigid relational structure." },
      { name: "Session-based Auth", reason: "Deliberately chosen over JWT for this use case. Sessions are easier to invalidate (important for shared school computers), more appropriate for a stateful institutional app, and simpler to manage for non-technical admins." },
    ],
    features: ["Student enrollment and profile management", "Staff management and class assignments", "Class, subject, and timetable management", "Daily attendance tracking per class", "Score entry and automatic grade calculation", "End-of-term report card generation", "Role-based dashboards: Admin, Teacher, Parent"],
    tags: ["React.js", "Node.js", "MongoDB", "Session Auth", "RBAC"],
  },
  {
    slug: "engineering-client-sites",
    num: "06",
    name: "Engineering Client Sites",
    tagline: "Production websites for engineering firms",
    shortDesc: "Client-facing websites for engineering-sector businesses with WhatsApp integration, quotation forms, video embedding, and full deployment.",
    problem: "Engineering firms in Nigeria lacked professional web presence — losing potential clients who searched online, couldn't get quotes easily, and had no way to showcase their work digitally.",
    solution: "Built and deployed production websites tailored for engineering sector clients. Each site included business-specific integrations: WhatsApp chat for instant client contact, quotation forms that email leads directly, and embedded project videos to showcase work.",
    stack: [
      { name: "React.js", reason: "Component-based approach allowed reusing navigation, footer, and UI elements across pages while keeping each section customizable per client." },
      { name: "Node.js + Express", reason: "Backend for handling form submissions, sending email notifications, and any server-side logic." },
      { name: "Tailwind CSS", reason: "Rapid UI development with consistent design — critical for client projects where speed of delivery matters." },
      { name: "WhatsApp Business API", reason: "Most Nigerian business clients communicate via WhatsApp. Embedding a WhatsApp chat button dramatically increased lead conversion for clients." },
    ],
    features: ["WhatsApp chat integration for instant client contact", "Quotation request forms with email notifications", "Embedded project showcase videos", "Mobile-responsive design", "SEO-optimized for local Nigerian search", "Full deployment and hosting setup"],
    tags: ["React.js", "Node.js", "Tailwind CSS", "WhatsApp API"],
  },
];

export const education = [
  {
    degree: "B.Eng, Naval Architecture & Marine Engineering",
    school: "University of Benin",
    location: "Benin City, Nigeria",
    year: "Expected 2027",
    note: "A unique academic background bridging software engineering with structural and mechanical engineering principles.",
  },
];
